use_frameworks!

platform :ios, '8.0'

target 'RGThirdSDKWrapper_Example' do
  pod 'RGThirdSDKWrapper', :path => '../'

  target 'RGThirdSDKWrapper_Tests' do
    inherit! :search_paths

    
  end
end
